trigger:
- master

pool:
  vmImage: 'macOS-10.15'

steps:
- task: MSBuild@1
  inputs:
    solution: 'Xamarin.RevenueCat.Android/Xamarin.RevenueCat.Android.csproj'
    msbuildVersion: '16.0'
    msbuildArchitecture: 'x64'
    configuration: 'Release'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'nuget.org thisisthekap connection'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'Xamarin.RevenueCat.Android/nugetoutput/*.nupkg;!Xamarin.RevenueCat.Android/nugetoutput/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org thisisthekap connection'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Xamarin.RevenueCat.Android'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'release-v*'
    assets: 'Xamarin.RevenueCat.Android/nugetoutput/*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
