trigger:
  branches:
    include:
      - refs/tags/release-v*

pr: none

pool:
  vmImage: 'macOS-11'

variables:
  - group: nuget.org

steps:

- bash: |
    echo "##vso[task.setvariable variable=bindingsVersion]$(cat Xamarin.RevenueCat.Android/Xamarin.RevenueCat.Android.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"

- bash: |
    echo "##vso[build.updatebuildnumber]production-xamarin-revenuecat-android-bindings-$(Build.SourceBranchName)-$(Build.BuildId)"

- bash: |
    if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
      echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
      exit 1
    fi

- bash: |
    cd Xamarin.RevenueCat.Android.Core.Strings
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Core.Strings: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Core.Utils
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Core.Utils: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Core.Public
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Core.Public: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Core.Common
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Core.Common: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Core.Feature.Subscriber.Attributes
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Core.Feature.Subscriber.Attributes: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Core.Feature.Identity
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Core.Feature.Identity: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Store.Google
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Store.Google: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Store.Amazon
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Store.Amazon: Build Release Nuget"

- bash: |
    cd Xamarin.RevenueCat.Android.Extensions
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Xamarin.RevenueCat.Android.Extensions: Build Release Nuget"

- bash: |
    ./copy-nugets.sh
  displayName: "Copy nugets to nugetoutput folder"

- bash: |
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Core.Strings.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Core.Utils.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Core.Public.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Core.Common.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Core.Feature.Subscriber.Attributes.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Core.Feature.Identity.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Store.Google.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Store.Amazon.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Xamarin.RevenueCat.Android.Extensions.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
  displayName: "Publish nuget packages to nuget.org"

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Xamarin.RevenueCat.Android'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Xamarin.RevenueCat.Android $(bindingsVersion)'
    assets: 'nugetoutput/Xamarin.RevenueCat.Android.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
